// 由 scripts/migrate.mjs 生成：磁盘相对路径 -> permalink URL 路径。勿手改。
// JSON 即合法 TS 对象字面量。
export const rewrites: Record<string, string> = {
  "guide/quickstart/简介.md": "pages/introduction/index.md",
  "guide/quickstart/使用场景.md": "pages/use-cases/index.md",
  "guide/quickstart/快速开始.md": "pages/quick-start/index.md",
  "guide/quickstart/动态刷新.md": "pages/dynamic-refresh/index.md",
  "guide/rulechain/说明.md": "pages/rule-chain-overview/index.md",
  "guide/rulechain/规则链.md": "pages/rule-chain/index.md",
  "guide/rulechain/消息.md": "pages/rule-chain-message/index.md",
  "guide/rulechain/规则节点.md": "pages/rule-node/index.md",
  "guide/rulechain/Relation Type.md": "pages/relation-type/index.md",
  "components/standard/说明.md": "pages/standard-components/index.md",
  "components/standard/common/ref.md": "pages/ref/index.md",
  "components/standard/common/groupAction.md": "pages/group-action/index.md",
  "components/standard/common/iterator.md": "pages/iterator/index.md",
  "components/standard/common/for.md": "pages/for/index.md",
  "components/standard/common/fork.md": "pages/fork/index.md",
  "components/standard/common/join.md": "pages/join/index.md",
  "components/standard/common/switch.md": "pages/switch/index.md",
  "components/standard/common/inclusive.md": "pages/inclusive/index.md",
  "components/standard/common/break.md": "pages/break/index.md",
  "components/standard/common/while.md": "pages/while/index.md",
  "components/standard/common/end.md": "pages/end/index.md",
  "components/standard/filter/jsFilter.md": "pages/js-filter/index.md",
  "components/standard/filter/fieldFilter.md": "pages/field-filter/index.md",
  "components/standard/filter/msgTypeSwitch.md": "pages/msg-type-switch/index.md",
  "components/standard/filter/jsSwitch.md": "pages/js-switch/index.md",
  "components/standard/filter/groupFilter.md": "pages/group-filter/index.md",
  "components/standard/filter/exprFilter.md": "pages/expr-filter/index.md",
  "components/standard/action/log.md": "pages/log/index.md",
  "components/standard/action/functions.md": "pages/functions/index.md",
  "components/standard/action/delay.md": "pages/delay/index.md",
  "components/standard/action/exec.md": "pages/exec/index.md",
  "components/standard/action/fetchNodeOutput.md": "pages/fetch-node-output/index.md",
  "components/standard/transform/jsTransform.md": "pages/js-transform/index.md",
  "components/standard/transform/exprTransform.md": "pages/expr-transform/index.md",
  "components/standard/transform/metadataTransform.md": "pages/metadata-transform/index.md",
  "components/standard/transform/template.md": "pages/template/index.md",
  "components/standard/external/restApiCall.md": "pages/rest-api-call/index.md",
  "components/standard/external/mqttClient.md": "pages/mqtt-client/index.md",
  "components/standard/external/sendMail.md": "pages/send-mail/index.md",
  "components/standard/external/dbClient.md": "pages/db-client/index.md",
  "components/standard/external/ssh.md": "pages/ssh/index.md",
  "components/standard/external/net.md": "pages/net/index.md",
  "components/standard/external/ws.md": "pages/ws/index.md",
  "components/standard/external/cacheSet.md": "pages/cache-set/index.md",
  "components/standard/external/cacheGet.md": "pages/cache-get/index.md",
  "components/standard/external/cacheDelete.md": "pages/cache-delete/index.md",
  "components/standard/flow/子规则链.md": "pages/sub-rule-chain/index.md",
  "components/extension/说明.md": "pages/extension-overview/index.md",
  "components/extension/filter/luaFilter.md": "pages/lua-filter/index.md",
  "components/extension/action/python.md": "pages/python-node/index.md",
  "components/extension/transform/luaTransform.md": "pages/lua-transform/index.md",
  "components/extension/external/redisClient.md": "pages/redis-client/index.md",
  "components/extension/external/kafkaProducer.md": "pages/kafka-producer/index.md",
  "components/extension/external/natsClient.md": "pages/nats-client/index.md",
  "components/extension/external/rabbitmqClient.md": "pages/rabbitmq-client/index.md",
  "components/extension/external/opengeminiWrite.md": "pages/opengemini-write/index.md",
  "components/extension/external/opengeminiQuery.md": "pages/opengemini-query/index.md",
  "components/extension/external/mongdbClient.md": "pages/mongodb-client/index.md",
  "components/extension/external/redisPub.md": "pages/redis-pub/index.md",
  "components/extension/external/grpcClient.md": "pages/grpc-client/index.md",
  "components/extension/external/openTelemetry.md": "pages/open-telemetry/index.md",
  "components/extension/external/beanstalkdWorkder.md": "pages/beanstalkd-worker/index.md",
  "components/extension/external/beanstalkdTube.md": "pages/beanstalkd-tube/index.md",
  "components/extension/external/wukongimSender.md": "pages/wukongim-sender/index.md",
  "components/extension/external/nsqClient.md": "pages/nsq-client/index.md",
  "components/extension/external/pulsarClient.md": "pages/pulsar-client/index.md",
  "components/extension/external/receiveEmail.md": "pages/receive-email/index.md",
  "components/extension/ai/components/智能体.md": "pages/ai-agent/index.md",
  "components/extension/ai/components/文本生成.md": "pages/llm/index.md",
  "components/extension/ai/components/图像生成.md": "pages/create-image/index.md",
  "components/extension/ai/components/意图识别.md": "pages/ai-intent/index.md",
  "components/extension/ai/components/本地意图识别.md": "pages/ai-local-intent/index.md",
  "components/extension/ai/components/MCP客户端.md": "pages/ai-mcp-client/index.md",
  "components/extension/ai/components/MCP服务端.md": "pages/ai-mcp-server/index.md",
  "components/extension/ci/gitClone.md": "pages/ci-git-clone/index.md",
  "components/extension/ci/gitCommit.md": "pages/ci-git-commit/index.md",
  "components/extension/ci/gitCreateTag.md": "pages/ci-git-create-tag/index.md",
  "components/extension/ci/gitPush.md": "pages/ci-git-push/index.md",
  "components/extension/ci/服务器监控.md": "pages/ci-server-monitoring/index.md",
  "components/extension/ci/gitLog.md": "pages/ci-git-log/index.md",
  "components/extension/iot/概览.md": "pages/iot-overview/index.md",
  "components/extension/iot/input-endpoint/endpoint-opcua.md": "pages/opcua-subscription/index.md",
  "components/extension/iot/input-endpoint/endpoint-snmp.md": "pages/endpoint-snmp/index.md",
  "components/extension/iot/input-endpoint/endpoint_modbus_server.md": "pages/endpoint-modbus-server/index.md",
  "components/extension/iot/input-endpoint/endpoint-hj212.md": "pages/endpoint-hj212/index.md",
  "components/extension/iot/protocol-acquisition/opcua_read.md": "pages/x-opcua-read/index.md",
  "components/extension/iot/protocol-acquisition/opcua_write.md": "pages/x-opcua-write/index.md",
  "components/extension/iot/protocol-acquisition/modbus.md": "pages/x-modbus/index.md",
  "components/extension/iot/protocol-acquisition/serial.md": "pages/x-serial/index.md",
  "components/extension/iot/protocol-acquisition/s7_read.md": "pages/x-s7-read/index.md",
  "components/extension/iot/protocol-acquisition/s7_write.md": "pages/x-s7-write/index.md",
  "components/extension/iot/protocol-acquisition/eip_read.md": "pages/x-eip-read/index.md",
  "components/extension/iot/protocol-acquisition/eip_write.md": "pages/x-eip-write/index.md",
  "components/extension/iot/protocol-acquisition/snmp_read.md": "pages/x-snmp-read/index.md",
  "components/extension/iot/protocol-acquisition/snmp_write.md": "pages/x-snmp-write/index.md",
  "components/extension/iot/protocol-acquisition/modbus_read.md": "pages/x-modbus-read/index.md",
  "components/extension/iot/protocol-acquisition/modbus_write.md": "pages/x-modbus-write/index.md",
  "components/extension/iot/protocol-acquisition/iot_read.md": "pages/x-iot-read/index.md",
  "components/extension/iot/protocol-acquisition/iot_write.md": "pages/x-iot-write/index.md",
  "components/extension/iot/protocol-acquisition/iec104_read.md": "pages/x-iec104-read/index.md",
  "components/extension/iot/protocol-acquisition/iec104_write.md": "pages/x-iec104-write/index.md",
  "components/extension/iot/protocol-acquisition/bacnet_read.md": "pages/x-bacnet-read/index.md",
  "components/extension/iot/protocol-acquisition/bacnet_write.md": "pages/x-bacnet-write/index.md",
  "components/extension/iot/protocol-acquisition/fins_read.md": "pages/x-fins/index.md",
  "components/extension/iot/protocol-acquisition/fins_write.md": "pages/x-fins-write/index.md",
  "components/extension/iot/protocol-acquisition/mc.md": "pages/x-mc/index.md",
  "components/extension/iot/protocol-acquisition/mc_read.md": "pages/x-mc-read/index.md",
  "components/extension/iot/protocol-acquisition/mc_write.md": "pages/x-mc-write/index.md",
  "components/extension/iot/protocol-acquisition/dlt645.md": "pages/x-dlt645/index.md",
  "components/extension/iot/protocol-acquisition/dlt645_read.md": "pages/x-dlt645-read/index.md",
  "components/extension/iot/protocol-acquisition/dlt645_write.md": "pages/x-dlt645-write/index.md",
  "components/extension/iot/tsdb/tsdb_write.md": "pages/x-tsdb-write/index.md",
  "components/extension/iot/tsdb/tsdb_query.md": "pages/x-tsdb-query/index.md",
  "components/extension/iot/tsdb/influxdb_write.md": "pages/x-influxdb-write/index.md",
  "components/extension/iot/tsdb/influxdb_query.md": "pages/x-influxdb-query/index.md",
  "components/extension/iot/tsdb/tdengine_write.md": "pages/x-tdengine-write/index.md",
  "components/extension/iot/tsdb/tdengine_query.md": "pages/x-tdengine-query/index.md",
  "components/extension/iot/tsdb/timescaledb_write.md": "pages/x-timescaledb-write/index.md",
  "components/extension/iot/tsdb/timescaledb_query.md": "pages/x-timescaledb-query/index.md",
  "components/extension/iot/tsdb/promremote_write.md": "pages/x-promremote-write/index.md",
  "components/extension/iot/control/timer.md": "pages/x-control-timer/index.md",
  "components/extension/iot/control/watchdog.md": "pages/x-control-watchdog/index.md",
  "components/extension/iot/场景示例.md": "pages/iot-scenarios/index.md",
  "components/extension/stream/说明.md": "pages/stream-computing/index.md",
  "components/extension/stream/streamAggregator.md": "pages/x-stream-aggregator/index.md",
  "components/extension/stream/streamTransform.md": "pages/x-stream-transform/index.md",
  "components/extension/discovery/概览.md": "pages/discovery-overview/index.md",
  "components/extension/discovery/service-call/nacos_service_call.md": "pages/x-nacos-service-call/index.md",
  "components/extension/discovery/config/nacos_config_get.md": "pages/x-nacos-config-get/index.md",
  "components/extension/discovery/config/endpoint_nacos.md": "pages/endpoint-nacos/index.md",
  "components/extension/discovery/config/nacos_config_set.md": "pages/x-nacos-config-set/index.md",
  "components/extension/file/file.md": "pages/file/index.md",
  "guide/custom-component/说明.md": "pages/custom-components-overview/index.md",
  "guide/custom-component/组件可视化配置.md": "pages/custom-component-visual/index.md",
  "guide/marketplace/动态组件.md": "pages/marketplace/index.md",
  "guide/marketplace/组件安装.md": "pages/dc-install/index.md",
  "guide/marketplace/组件发布.md": "pages/dc-publish/index.md",
  "guide/visualization/说明.md": "pages/visualization-overview/index.md",
  "guide/visualization/获取组件配置表单.md": "pages/get-component-form/index.md",
  "guide/visualization/组件配置表单约定.md": "pages/component-form-conventions/index.md",
  "guide/visualization/获取规则链配置.md": "pages/get-rule-chain-config/index.md",
  "guide/visualization/获取规则链节点配置.md": "pages/get-rule-node-config/index.md",
  "guide/visualization/批量初始化规则链.md": "pages/batch-init-rule-chains/index.md",
  "guide/visualization/删除规则链实例.md": "pages/delete-rule-chain-instance/index.md",
  "guide/visualization/保存规则链坐标信息.md": "pages/save-rule-chain-layout/index.md",
  "guide/aop/说明.md": "pages/aop-overview/index.md",
  "guide/aop/Before Advice.md": "pages/before-advice/index.md",
  "guide/aop/After Advice.md": "pages/after-advice/index.md",
  "guide/aop/Around Advice.md": "pages/around-advice/index.md",
  "guide/aop/Start Advice.md": "pages/start-advice/index.md",
  "guide/aop/End Advice.md": "pages/end-advice/index.md",
  "guide/aop/Completed Advice.md": "pages/completed-advice/index.md",
  "guide/aop/OnChainBeforeInit Advice.md": "pages/on-chain-before-init-advice/index.md",
  "guide/aop/OnNodeBeforeInit Advice.md": "pages/on-node-before-init-advice/index.md",
  "guide/aop/OnCreated Advice.md": "pages/on-created-advice/index.md",
  "guide/aop/OnReload Advice.md": "pages/on-reload-advice/index.md",
  "guide/aop/OnDestroy Advice.md": "pages/on-destroy-advice/index.md",
  "guide/aop/builtin-aspect/Debug Aspect.md": "pages/debug-aspect/index.md",
  "guide/aop/builtin-aspect/Fallback Aspect.md": "pages/fallback-aspect/index.md",
  "guide/aop/builtin-aspect/Metrics Aspect.md": "pages/metrics-aspect/index.md",
  "guide/aop/builtin-aspect/Limiter Aspect.md": "pages/limiter-aspect/index.md",
  "guide/aop/builtin-aspect/Validator Aspect.md": "pages/validator-aspect/index.md",
  "guide/trigger/说明.md": "pages/trigger-overview/index.md",
  "guide/advanced/config.md": "pages/config/index.md",
  "guide/advanced/Options.md": "pages/options/index.md",
  "guide/advanced/共享数据.md": "pages/share-data/index.md",
  "guide/advanced/执行规则链.md": "pages/execute-rule-chain/index.md",
  "guide/advanced/组件配置变量.md": "pages/component-configuration-variables/index.md",
  "guide/advanced/组件连接复用.md": "pages/component-connection-reuse/index.md",
  "guide/advanced/性能.md": "pages/performance/index.md",
  "ai/概述.md": "pages/ai-agent-overview/index.md",
  "ai/架构设计.md": "pages/ai-agent-architecture/index.md",
  "ai/智能体节点.md": "pages/ai-agent-node/index.md",
  "ai/工具系统.md": "pages/ai-agent-tools/index.md",
  "ai/切面框架.md": "pages/ai-agent-aspect/index.md",
  "ai/会话管理.md": "pages/ai-agent-session/index.md",
  "ai/开发指南.md": "pages/ai-agent-guide/index.md",
  "ai/编排案例.md": "pages/ai-agent-orchestration/index.md",
  "ai/应用案例.md": "pages/ai-agent-case-study/index.md",
  "server/概述与快速开始.md": "pages/rulego-server/index.md",
  "server/安装与部署.md": "pages/rulego-server-install/index.md",
  "server/用户认证与权限.md": "pages/rulego-server-auth/index.md",
  "server/REST-API参考.md": "pages/rulego-server-api/index.md",
  "server/MCP服务.md": "pages/rulego-server-mcp/index.md",
  "server/AI功能.md": "pages/rulego-server-ai/index.md",
  "server/组件市场.md": "pages/rulego-server-marketplace/index.md",
  "server/运行日志.md": "pages/rulego-server-runlog/index.md",
  "server/国际化.md": "pages/rulego-server-i18n/index.md",
  "server/二次开发.md": "pages/rulego-server-development/index.md",
  "server/规则链部署与调用.md": "pages/rulego-server-deploy-rule-chain/index.md",
  "server/visual-editor/可视化编辑器.md": "pages/rulego-server-editor/index.md",
  "server/visual-editor/AI助手使用教程.md": "pages/rulego-server-ai-tutorial/index.md",
  "server/visual-editor/调试规则链.md": "pages/rulego-server-debug/index.md",
  "server/visual-editor/创建智能体.md": "pages/rulego-server-create-agent/index.md",
  "guide/faq/关于规则引擎执行中断恢复.md": "pages/interrupt-recovery/index.md",
  "guide/faq/FAQ.md": "pages/faq/index.md",
  "guide/faq/注册gRPC反射服务示例.md": "pages/grpc-reflection-example/index.md",
  "endpoint/说明.md": "pages/endpoint-overview/index.md",
  "endpoint/快速入门.md": "pages/endpoint-quickstart/index.md",
  "endpoint/路由.md": "pages/endpoint-router/index.md",
  "endpoint/DSL.md": "pages/endpoint-dsl/index.md",
  "endpoint/API.md": "pages/endpoint-api/index.md",
  "endpoint/options.md": "pages/endpoint-options/index.md",
  "endpoint/components/rest endpint.md": "pages/endpoint-rest/index.md",
  "endpoint/components/websocket endpint.md": "pages/endpoint-websocket/index.md",
  "endpoint/components/mqtt endpint.md": "pages/endpoint-mqtt/index.md",
  "endpoint/components/schedule endpint.md": "pages/endpoint-schedule/index.md",
  "endpoint/components/net endpint.md": "pages/endpoint-net/index.md",
  "endpoint/components/kafka endpint.md": "pages/endpoint-kafka/index.md",
  "endpoint/components/nats endpint.md": "pages/endpoint-nats/index.md",
  "endpoint/components/redis sub endpint.md": "pages/endpoint-redis-sub/index.md",
  "endpoint/components/redis stream endpint.md": "pages/endpoint-redis-stream/index.md",
  "endpoint/components/rabbitmq endpint.md": "pages/endpoint-rabbitmq/index.md",
  "endpoint/components/mysql_cdc endpint.md": "pages/mysql-cdc/index.md",
  "endpoint/components/opcua endpint.md": "pages/endpoint-opcua/index.md",
  "endpoint/components/grpc stream endpint.md": "pages/endpoint-grpc-stream/index.md",
  "endpoint/components/beanstalkd endpint.md": "pages/endpoint-beanstalkd/index.md",
  "endpoint/components/wukongim endpint.md": "pages/endpoint-wukongim/index.md",
  "endpoint/components/扩展endpoint.md": "pages/endpoint-extension/index.md",
  "endpoint/components/nsq endpint.md": "pages/endpoint-nsq/index.md",
  "endpoint/components/pulsar endpint.md": "pages/endpoint-pulsar/index.md",
  "endpoint/components/net client endpint.md": "pages/endpoint-net-client/index.md",
  "endpoint/components/websocket client endpint.md": "pages/endpoint-ws-client/index.md",
  "streamsql/概述.md": "pages/streamsql-overview/index.md",
  "streamsql/快速开始.md": "pages/streamsql-quickstart/index.md",
  "streamsql/核心概念.md": "pages/streamsql-concepts/index.md",
  "streamsql/SQL参考.md": "pages/streamsql-sql/index.md",
  "streamsql/API参考.md": "pages/streamsql-api/index.md",
  "streamsql/RuleGo集成.md": "pages/streamsql-rulego/index.md",
  "streamsql/加入社区讨论.md": "pages/streamsql-community/index.md",
  "streamsql/Schema校验.md": "pages/streamsql-schema/index.md",
  "streamsql/分析函数.md": "pages/streamsql-analytic/index.md",
  "streamsql/进阶示例.md": "pages/streamsql-advanced-examples/index.md",
  "streamsql/模式识别.md": "pages/streamsql-cep/index.md",
  "streamsql/functions/聚合函数.md": "pages/streamsql-aggregate-functions/index.md",
  "streamsql/functions/分析函数.md": "pages/streamsql-analytical-functions/index.md",
  "streamsql/functions/窗口函数.md": "pages/streamsql-window-functions/index.md",
  "streamsql/functions/数学函数.md": "pages/streamsql-math-functions/index.md",
  "streamsql/functions/字符串函数.md": "pages/streamsql-string-functions/index.md",
  "streamsql/functions/类型转换函数.md": "pages/streamsql-conversion-functions/index.md",
  "streamsql/functions/时间日期函数.md": "pages/streamsql-datetime-functions/index.md",
  "streamsql/functions/JSON函数.md": "pages/streamsql-json-functions/index.md",
  "streamsql/functions/哈希函数.md": "pages/streamsql-hash-functions/index.md",
  "streamsql/functions/数组函数.md": "pages/streamsql-array-functions/index.md",
  "streamsql/functions/类型检查函数.md": "pages/streamsql-type-check-functions/index.md",
  "streamsql/functions/条件函数.md": "pages/streamsql-conditional-functions/index.md",
  "streamsql/functions/多行函数.md": "pages/streamsql-multirow-functions/index.md",
  "streamsql/functions/表达式函数.md": "pages/streamsql-expression-functions/index.md",
  "streamsql/functions/自定义函数.md": "pages/streamsql-functions/index.md",
  "streamsql/case-studies/概述.md": "pages/streamsql-cases-overview/index.md",
  "streamsql/case-studies/流表JOIN元数据增强.md": "pages/streamsql-case-join/index.md",
  "streamsql/case-studies/会话窗口与设备在线.md": "pages/streamsql-case-session/index.md",
  "streamsql/case-studies/变更数据捕获.md": "pages/streamsql-cdc/index.md",
  "streamsql/case-studies/滑动窗口与持续检测.md": "pages/streamsql-case-sliding/index.md",
  "streamsql/case-studies/数据过滤与转换.md": "pages/streamsql-case-filter/index.md",
  "streamsql/case-studies/IoT温度告警与指标聚合.md": "pages/streamsql-case-iot-temperature/index.md",
  "streamsql/case-studies/设备故障模式识别.md": "pages/streamsql-case-cep/index.md",
  "support/支持.md": "pages/support/index.md",
  "en/guide/quickstart/Introduction.md": "en/pages/introduction/index.md",
  "en/guide/quickstart/Use Cases.md": "en/pages/use-cases/index.md",
  "en/guide/quickstart/Quick Start.md": "en/pages/quick-start/index.md",
  "en/guide/quickstart/Dynamic Refresh.md": "en/pages/dynamic-refresh/index.md",
  "en/guide/rulechain/Description.md": "en/pages/rule-chain-overview/index.md",
  "en/guide/rulechain/Rule Chain.md": "en/pages/rule-chain/index.md",
  "en/guide/rulechain/Message.md": "en/pages/rule-chain-message/index.md",
  "en/guide/rulechain/Rule Node.md": "en/pages/rule-node/index.md",
  "en/guide/rulechain/Relation Type.md": "en/pages/relation-type/index.md",
  "en/components/standard/Description.md": "en/pages/standard-components/index.md",
  "en/components/standard/common/ref.md": "en/pages/ref/index.md",
  "en/components/standard/common/groupAction.md": "en/pages/group-action/index.md",
  "en/components/standard/common/iterator.md": "en/pages/iterator/index.md",
  "en/components/standard/common/for.md": "en/pages/for/index.md",
  "en/components/standard/common/fork.md": "en/pages/fork/index.md",
  "en/components/standard/common/join.md": "en/pages/join/index.md",
  "en/components/standard/common/switch.md": "en/pages/switch/index.md",
  "en/components/standard/common/inclusive.md": "en/pages/inclusive/index.md",
  "en/components/standard/common/break.md": "en/pages/break/index.md",
  "en/components/standard/common/while.md": "en/pages/while/index.md",
  "en/components/standard/common/end.md": "en/pages/end/index.md",
  "en/components/standard/filter/jsFilter.md": "en/pages/js-filter/index.md",
  "en/components/standard/filter/fieldFilter.md": "en/pages/field-filter/index.md",
  "en/components/standard/filter/msgTypeSwitch.md": "en/pages/msg-type-switch/index.md",
  "en/components/standard/filter/jsSwitch.md": "en/pages/js-switch/index.md",
  "en/components/standard/filter/groupFilter.md": "en/pages/group-filter/index.md",
  "en/components/standard/filter/exprFilter.md": "en/pages/expr-filter/index.md",
  "en/components/standard/action/log.md": "en/pages/log/index.md",
  "en/components/standard/action/functions.md": "en/pages/functions/index.md",
  "en/components/standard/action/delay.md": "en/pages/delay/index.md",
  "en/components/standard/action/exec.md": "en/pages/exec/index.md",
  "en/components/standard/action/fetchNodeOutput.md": "en/pages/fetch-node-output/index.md",
  "en/components/standard/transform/jsTransform.md": "en/pages/js-transform/index.md",
  "en/components/standard/transform/exprTransform.md": "en/pages/expr-transform/index.md",
  "en/components/standard/transform/metadataTransform.md": "en/pages/metadata-transform/index.md",
  "en/components/standard/transform/template.md": "en/pages/template/index.md",
  "en/components/standard/external/restApiCall.md": "en/pages/rest-api-call/index.md",
  "en/components/standard/external/mqttClient.md": "en/pages/mqtt-client/index.md",
  "en/components/standard/external/sendMail.md": "en/pages/send-mail/index.md",
  "en/components/standard/external/dbClient.md": "en/pages/db-client/index.md",
  "en/components/standard/external/ssh.md": "en/pages/ssh/index.md",
  "en/components/standard/external/net.md": "en/pages/net/index.md",
  "en/components/standard/external/ws.md": "en/pages/ws/index.md",
  "en/components/standard/external/cacheSet.md": "en/pages/cache-set/index.md",
  "en/components/standard/external/cacheGet.md": "en/pages/cache-get/index.md",
  "en/components/standard/external/cacheDelete.md": "en/pages/cache-delete/index.md",
  "en/components/standard/flow/Sub Rule Chain.md": "en/pages/sub-rule-chain/index.md",
  "en/components/extension/Description.md": "en/pages/extension-overview/index.md",
  "en/components/extension/filter/luaFilter.md": "en/pages/lua-filter/index.md",
  "en/components/extension/action/python.md": "en/pages/python-node/index.md",
  "en/components/extension/transform/luaTransform.md": "en/pages/lua-transform/index.md",
  "en/components/extension/external/redisClient.md": "en/pages/redis-client/index.md",
  "en/components/extension/external/kafkaProducer.md": "en/pages/kafka-producer/index.md",
  "en/components/extension/external/natsClient.md": "en/pages/nats-client/index.md",
  "en/components/extension/external/rabbitmqClient.md": "en/pages/rabbitmq-client/index.md",
  "en/components/extension/external/opengeminiWrite.md": "en/pages/opengemini-write/index.md",
  "en/components/extension/external/opengeminiQuery.md": "en/pages/opengemini-query/index.md",
  "en/components/extension/external/mongdbClient.md": "en/pages/mongodb-client/index.md",
  "en/components/extension/external/redisPub.md": "en/pages/redis-pub/index.md",
  "en/components/extension/external/grpcClient.md": "en/pages/grpc-client/index.md",
  "en/components/extension/external/openTelemetry.md": "en/pages/open-telemetry/index.md",
  "en/components/extension/external/beanstalkdWorkder.md": "en/pages/beanstalkd-worker/index.md",
  "en/components/extension/external/beanstalkdTube.md": "en/pages/beanstalkd-tube/index.md",
  "en/components/extension/external/wukongimSender.md": "en/pages/wukongim-sender/index.md",
  "en/components/extension/external/nsqClient.md": "en/pages/nsq-client/index.md",
  "en/components/extension/external/pulsarClient.md": "en/pages/pulsar-client/index.md",
  "en/components/extension/external/receiveEmail.md": "en/pages/receive-email/index.md",
  "en/components/extension/ai/generate-text.md": "en/pages/llm/index.md",
  "en/components/extension/ai/generate-image.md": "en/pages/create-image/index.md",
  "en/components/extension/ci/gitClone.md": "en/pages/ci-git-clone/index.md",
  "en/components/extension/ci/gitCommit.md": "en/pages/ci-git-commit/index.md",
  "en/components/extension/ci/gitCreateTag.md": "en/pages/ci-git-create-tag/index.md",
  "en/components/extension/ci/gitPush.md": "en/pages/ci-git-push/index.md",
  "en/components/extension/ci/Server Metrics Monitoring.md": "en/pages/ci-server-monitoring/index.md",
  "en/components/extension/ci/gitLog.md": "en/pages/ci-git-log/index.md",
  "en/components/extension/iot/overview.md": "en/pages/iot-overview/index.md",
  "en/components/extension/iot/input-endpoint/endpoint-opcua.md": "en/pages/opcua-subscription/index.md",
  "en/components/extension/iot/input-endpoint/endpoint-snmp.md": "en/pages/endpoint-snmp/index.md",
  "en/components/extension/iot/input-endpoint/endpoint_modbus_server.md": "en/pages/endpoint-modbus-server/index.md",
  "en/components/extension/iot/protocol-acquisition/opcua_read.md": "en/pages/x-opcua-read/index.md",
  "en/components/extension/iot/protocol-acquisition/opcua_write.md": "en/pages/x-opcua-write/index.md",
  "en/components/extension/iot/protocol-acquisition/modbus.md": "en/pages/x-modbus/index.md",
  "en/components/extension/iot/protocol-acquisition/serial.md": "en/pages/x-serial/index.md",
  "en/components/extension/iot/protocol-acquisition/s7_read.md": "en/pages/x-s7-read/index.md",
  "en/components/extension/iot/protocol-acquisition/s7_write.md": "en/pages/x-s7-write/index.md",
  "en/components/extension/iot/protocol-acquisition/eip_read.md": "en/pages/x-eip-read/index.md",
  "en/components/extension/iot/protocol-acquisition/eip_write.md": "en/pages/x-eip-write/index.md",
  "en/components/extension/iot/protocol-acquisition/snmp_read.md": "en/pages/x-snmp-read/index.md",
  "en/components/extension/iot/protocol-acquisition/snmp_write.md": "en/pages/x-snmp-write/index.md",
  "en/components/extension/iot/protocol-acquisition/modbus_read.md": "en/pages/x-modbus-read/index.md",
  "en/components/extension/iot/protocol-acquisition/modbus_write.md": "en/pages/x-modbus-write/index.md",
  "en/components/extension/iot/protocol-acquisition/iot_read.md": "en/pages/x-iot-read/index.md",
  "en/components/extension/iot/protocol-acquisition/iot_write.md": "en/pages/x-iot-write/index.md",
  "en/components/extension/iot/protocol-acquisition/iec104_read.md": "en/pages/x-iec104-read/index.md",
  "en/components/extension/iot/protocol-acquisition/iec104_write.md": "en/pages/x-iec104-write/index.md",
  "en/components/extension/iot/protocol-acquisition/fins.md": "en/pages/x-fins/index.md",
  "en/components/extension/iot/protocol-acquisition/fins_read.md": "en/pages/x-fins-read/index.md",
  "en/components/extension/iot/protocol-acquisition/fins_write.md": "en/pages/x-fins-write/index.md",
  "en/components/extension/iot/protocol-acquisition/mc.md": "en/pages/x-mc/index.md",
  "en/components/extension/iot/protocol-acquisition/mc_read.md": "en/pages/x-mc-read/index.md",
  "en/components/extension/iot/protocol-acquisition/mc_write.md": "en/pages/x-mc-write/index.md",
  "en/components/extension/iot/protocol-acquisition/dlt645.md": "en/pages/x-dlt645/index.md",
  "en/components/extension/iot/protocol-acquisition/dlt645_read.md": "en/pages/x-dlt645-read/index.md",
  "en/components/extension/iot/protocol-acquisition/dlt645_write.md": "en/pages/x-dlt645-write/index.md",
  "en/components/extension/iot/protocol-acquisition/bacnet_read.md": "en/pages/x-bacnet-read/index.md",
  "en/components/extension/iot/protocol-acquisition/bacnet_write.md": "en/pages/x-bacnet-write/index.md",
  "en/components/extension/iot/tsdb/tsdb_write.md": "en/pages/x-tsdb-write/index.md",
  "en/components/extension/iot/tsdb/tsdb_query.md": "en/pages/x-tsdb-query/index.md",
  "en/components/extension/iot/control/timer.md": "en/pages/x-control-timer/index.md",
  "en/components/extension/iot/control/watchdog.md": "en/pages/x-control-watchdog/index.md",
  "en/components/extension/iot/scenarios.md": "en/pages/iot-scenarios/index.md",
  "en/components/extension/stream/Description.md": "en/pages/stream-computing/index.md",
  "en/components/extension/stream/streamAggregator.md": "en/pages/x-stream-aggregator/index.md",
  "en/components/extension/stream/streamTransform.md": "en/pages/x-stream-transform/index.md",
  "en/components/extension/discovery/Overview.md": "en/pages/discovery-overview/index.md",
  "en/components/extension/discovery/service-call/nacos_service_call.md": "en/pages/x-nacos-service-call/index.md",
  "en/components/extension/discovery/config/endpoint_nacos.md": "en/pages/endpoint-nacos/index.md",
  "en/components/extension/discovery/config/nacos_config_get.md": "en/pages/x-nacos-config-get/index.md",
  "en/components/extension/discovery/config/nacos_config_set.md": "en/pages/x-nacos-config-set/index.md",
  "en/components/extension/file/file.md": "en/pages/file/index.md",
  "en/guide/custom-component/Description.md": "en/pages/custom-components-overview/index.md",
  "en/guide/custom-component/Component Visual Configuration.md": "en/pages/custom-component-visual/index.md",
  "en/guide/marketplace/Dynamic Components.md": "en/pages/marketplace/index.md",
  "en/guide/marketplace/Dynamic Component Installation.md": "en/pages/dc-install/index.md",
  "en/guide/marketplace/Dynamic Component Publishing.md": "en/pages/dc-publish/index.md",
  "en/guide/visualization/Description.md": "en/pages/visualization-overview/index.md",
  "en/guide/visualization/Get Component Configuration Forms.md": "en/pages/get-component-form/index.md",
  "en/guide/visualization/Component Form Conventions.md": "en/pages/component-form-conventions/index.md",
  "en/guide/visualization/Get Rule Chain Configuration.md": "en/pages/get-rule-chain-config/index.md",
  "en/guide/visualization/Get Rule Chain Node Configuration.md": "en/pages/get-rule-node-config/index.md",
  "en/guide/visualization/Batch Initialize Rule Chain.md": "en/pages/batch-init-rule-chains/index.md",
  "en/guide/visualization/Delete Rule Chain Instance.md": "en/pages/delete-rule-chain-instance/index.md",
  "en/guide/visualization/Save Rule Chain Coordinate Information.md": "en/pages/save-rule-chain-layout/index.md",
  "en/guide/aop/Description.md": "en/pages/aop-overview/index.md",
  "en/guide/aop/Before Advice.md": "en/pages/before-advice/index.md",
  "en/guide/aop/After Advice.md": "en/pages/after-advice/index.md",
  "en/guide/aop/Around Advice.md": "en/pages/around-advice/index.md",
  "en/guide/aop/Start Advice.md": "en/pages/start-advice/index.md",
  "en/guide/aop/End Advice.md": "en/pages/end-advice/index.md",
  "en/guide/aop/Completed Advice.md": "en/pages/completed-advice/index.md",
  "en/guide/aop/OnChainBeforeInit Advice.md": "en/pages/on-chain-before-init-advice/index.md",
  "en/guide/aop/OnNodeBeforeInit Advice.md": "en/pages/on-node-before-init-advice/index.md",
  "en/guide/aop/OnCreated Advice.md": "en/pages/on-created-advice/index.md",
  "en/guide/aop/OnReload Advice.md": "en/pages/on-reload-advice/index.md",
  "en/guide/aop/OnDestroy Advice.md": "en/pages/on-destroy-advice/index.md",
  "en/guide/aop/builtin-aspect/Debug Aspect.md": "en/pages/debug-aspect/index.md",
  "en/guide/aop/builtin-aspect/Fallback Aspect.md": "en/pages/fallback-aspect/index.md",
  "en/guide/aop/builtin-aspect/Metrics Aspect.md": "en/pages/metrics-aspect/index.md",
  "en/guide/aop/builtin-aspect/Limiter Aspect.md": "en/pages/limiter-aspect/index.md",
  "en/guide/aop/builtin-aspect/Validator Aspect.md": "en/pages/validator-aspect/index.md",
  "en/guide/trigger/Introduction.md": "en/pages/trigger-overview/index.md",
  "en/guide/advanced/Config.md": "en/pages/config/index.md",
  "en/guide/advanced/Options.md": "en/pages/options/index.md",
  "en/guide/advanced/Share data.md": "en/pages/share-data/index.md",
  "en/guide/advanced/Execute Rule Chain.md": "en/pages/execute-rule-chain/index.md",
  "en/guide/advanced/Component Configuration Variables.md": "en/pages/component-configuration-variables/index.md",
  "en/guide/advanced/Component Connection Reuse.md": "en/pages/component-connection-reuse/index.md",
  "en/guide/advanced/Performance.md": "en/pages/performance/index.md",
  "en/guide/advanced/Other.md": "en/pages/interrupt-recovery/index.md",
  "en/ai/Overview.md": "en/pages/ai-agent-overview/index.md",
  "en/ai/Architecture Design.md": "en/pages/ai-agent-architecture/index.md",
  "en/ai/Agent Node.md": "en/pages/ai-agent-node/index.md",
  "en/ai/Tool System.md": "en/pages/ai-agent-tools/index.md",
  "en/ai/Aspect Framework.md": "en/pages/ai-agent-aspect/index.md",
  "en/ai/Session Management.md": "en/pages/ai-agent-session/index.md",
  "en/ai/Development Guide.md": "en/pages/ai-agent-guide/index.md",
  "en/ai/Orchestration Examples.md": "en/pages/ai-agent-orchestration/index.md",
  "en/ai/Application Case Study.md": "en/pages/ai-agent-case-study/index.md",
  "en/server/Overview and Quick Start.md": "en/pages/rulego-server/index.md",
  "en/server/Installation and Deployment.md": "en/pages/rulego-server-install/index.md",
  "en/server/Authentication and Authorization.md": "en/pages/rulego-server-auth/index.md",
  "en/server/REST API Reference.md": "en/pages/rulego-server-api/index.md",
  "en/server/MCP Service.md": "en/pages/rulego-server-mcp/index.md",
  "en/server/AI Features.md": "en/pages/rulego-server-ai/index.md",
  "en/server/Component Marketplace.md": "en/pages/rulego-server-marketplace/index.md",
  "en/server/Run Logs.md": "en/pages/rulego-server-runlog/index.md",
  "en/server/Internationalization.md": "en/pages/rulego-server-i18n/index.md",
  "en/server/Extension Development.md": "en/pages/rulego-server-development/index.md",
  "en/server/Deploying and Invoking Rule Chains.md": "en/pages/rulego-server-deploy-rule-chain/index.md",
  "en/server/visual-editor/Visual Editor.md": "en/pages/rulego-server-editor/index.md",
  "en/server/visual-editor/AI Assistant Tutorial.md": "en/pages/rulego-server-ai-tutorial/index.md",
  "en/server/visual-editor/Debugging Rule Chains.md": "en/pages/rulego-server-debug/index.md",
  "en/server/visual-editor/Creating an Agent.md": "en/pages/rulego-server-create-agent/index.md",
  "en/guide/faq/FAQ.md": "en/pages/faq/index.md",
  "en/endpoint/Description.md": "en/pages/endpoint-overview/index.md",
  "en/endpoint/Quick Start.md": "en/pages/endpoint-quickstart/index.md",
  "en/endpoint/Router.md": "en/pages/endpoint-router/index.md",
  "en/endpoint/DSL.md": "en/pages/endpoint-dsl/index.md",
  "en/endpoint/API.md": "en/pages/endpoint-api/index.md",
  "en/endpoint/options.md": "en/pages/endpoint-options/index.md",
  "en/endpoint/components/rest endpint.md": "en/pages/endpoint-rest/index.md",
  "en/endpoint/components/websocket endpint.md": "en/pages/endpoint-websocket/index.md",
  "en/endpoint/components/mqtt endpint.md": "en/pages/endpoint-mqtt/index.md",
  "en/endpoint/components/schedule endpint.md": "en/pages/endpoint-schedule/index.md",
  "en/endpoint/components/net endpint.md": "en/pages/endpoint-net/index.md",
  "en/endpoint/components/kafka endpint.md": "en/pages/endpoint-kafka/index.md",
  "en/endpoint/components/nats endpint.md": "en/pages/endpoint-nats/index.md",
  "en/endpoint/components/redis sub endpint.md": "en/pages/endpoint-redis-sub/index.md",
  "en/endpoint/components/redis stream endpint.md": "en/pages/endpoint-redis-stream/index.md",
  "en/endpoint/components/rabbitmq endpint.md": "en/pages/endpoint-rabbitmq/index.md",
  "en/endpoint/components/mysql_cdc endpint.md": "en/pages/mysql-cdc/index.md",
  "en/endpoint/components/opcua endpint.md": "en/pages/endpoint-opcua/index.md",
  "en/endpoint/components/grpc stream endpint.md": "en/pages/endpoint-grpc-stream/index.md",
  "en/endpoint/components/beanstalkd enpoint.md": "en/pages/endpoint-beanstalkd/index.md",
  "en/endpoint/components/wukongim endpint.md": "en/pages/endpoint-wukongim/index.md",
  "en/endpoint/components/Extend Endpoint.md": "en/pages/endpoint-extension/index.md",
  "en/endpoint/components/nsq endpint.md": "en/pages/endpoint-nsq/index.md",
  "en/endpoint/components/pulsar endpint.md": "en/pages/endpoint-pulsar/index.md",
  "en/endpoint/components/net client endpint.md": "en/pages/endpoint-net-client/index.md",
  "en/endpoint/components/websocket client endpint.md": "en/pages/endpoint-ws-client/index.md",
  "en/support/Support.md": "en/pages/support/index.md",
  "en/streamsql/overview.md": "en/pages/streamsql-overview/index.md",
  "en/streamsql/quickstart.md": "en/pages/streamsql-quickstart/index.md",
  "en/streamsql/core-concepts.md": "en/pages/streamsql-concepts/index.md",
  "en/streamsql/sql-reference.md": "en/pages/streamsql-sql/index.md",
  "en/streamsql/api-reference.md": "en/pages/streamsql-api/index.md",
  "en/streamsql/rulego-integration.md": "en/pages/streamsql-rulego/index.md",
  "en/streamsql/schema-validation.md": "en/pages/streamsql-schema/index.md",
  "en/streamsql/advanced-examples.md": "en/pages/streamsql-advanced-examples/index.md",
  "en/streamsql/pattern-matching.md": "en/pages/streamsql-cep/index.md",
  "en/streamsql/functions/aggregate-functions.md": "en/pages/streamsql-aggregate-functions/index.md",
  "en/streamsql/functions/analytical-functions.md": "en/pages/streamsql-analytical-functions/index.md",
  "en/streamsql/functions/window-functions.md": "en/pages/streamsql-window-functions/index.md",
  "en/streamsql/functions/math-functions.md": "en/pages/streamsql-math-functions/index.md",
  "en/streamsql/functions/string-functions.md": "en/pages/streamsql-string-functions/index.md",
  "en/streamsql/functions/conversion-functions.md": "en/pages/streamsql-conversion-functions/index.md",
  "en/streamsql/functions/datetime-functions.md": "en/pages/streamsql-datetime-functions/index.md",
  "en/streamsql/functions/json-functions.md": "en/pages/streamsql-json-functions/index.md",
  "en/streamsql/functions/hash-functions.md": "en/pages/streamsql-hash-functions/index.md",
  "en/streamsql/functions/array-functions.md": "en/pages/streamsql-array-functions/index.md",
  "en/streamsql/functions/type-check-functions.md": "en/pages/streamsql-type-check-functions/index.md",
  "en/streamsql/functions/conditional-functions.md": "en/pages/streamsql-conditional-functions/index.md",
  "en/streamsql/functions/multirow-functions.md": "en/pages/streamsql-multirow-functions/index.md",
  "en/streamsql/functions/expression-functions.md": "en/pages/streamsql-expression-functions/index.md",
  "en/streamsql/functions/custom-functions.md": "en/pages/streamsql-functions/index.md",
  "en/streamsql/case-studies/case-studies-overview.md": "en/pages/streamsql-cases-overview/index.md",
  "en/streamsql/case-studies/stream-table-join.md": "en/pages/streamsql-case-join/index.md",
  "en/streamsql/case-studies/session-window.md": "en/pages/streamsql-case-session/index.md",
  "en/streamsql/case-studies/change-data-capture.md": "en/pages/streamsql-cdc/index.md",
  "en/streamsql/case-studies/sliding-window.md": "en/pages/streamsql-case-sliding/index.md",
  "en/streamsql/case-studies/data-filtering.md": "en/pages/streamsql-case-filter/index.md",
  "en/streamsql/case-studies/iot-temperature-alerting.md": "en/pages/streamsql-case-iot-temperature/index.md",
  "en/streamsql/case-studies/device-fault-pattern-recognition.md": "en/pages/streamsql-case-cep/index.md",
  "en/components/extension/iot/input-endpoint/endpoint-hj212.md": "en/pages/endpoint-hj212/index.md",
  "en/components/extension/iot/tsdb/influxdb_write.md": "en/pages/x-influxdb-write/index.md",
  "en/components/extension/iot/tsdb/influxdb_query.md": "en/pages/x-influxdb-query/index.md",
  "en/components/extension/iot/tsdb/tdengine_write.md": "en/pages/x-tdengine-write/index.md",
  "en/components/extension/iot/tsdb/tdengine_query.md": "en/pages/x-tdengine-query/index.md",
  "en/components/extension/iot/tsdb/timescaledb_write.md": "en/pages/x-timescaledb-write/index.md",
  "en/components/extension/iot/tsdb/timescaledb_query.md": "en/pages/x-timescaledb-query/index.md",
  "en/components/extension/iot/tsdb/promremote_write.md": "en/pages/x-promremote-write/index.md",
  "en/guide/faq/grpc-reflection-example.md": "en/pages/grpc-reflection-example/index.md",
  "en/streamsql/analytic-functions.md": "en/pages/streamsql-analytic/index.md",
  "en/streamsql/join-community.md": "en/pages/streamsql-community/index.md",
  "en/community/index.md": "en/pages/community/index.md",
  "community/index.md": "pages/community/index.md",
  "components/extension/ai/components/Jev决策.md": "pages/ai-jev/index.md",
  "components/extension/ai/components/Jev过滤.md": "pages/ai-jev-filter/index.md",
  "guide/advanced/09.至多一次执行.md": "pages/locker/index.md",
  "server/12.分布式部署.md": "pages/rulego-server-distributed/index.md",
  "en/components/extension/ai/components/agent.md": "en/pages/ai-agent/index.md",
  "en/components/extension/ai/components/intent.md": "en/pages/ai-intent/index.md",
  "en/components/extension/ai/components/local-intent.md": "en/pages/ai-local-intent/index.md",
  "en/components/extension/ai/components/mcp-client.md": "en/pages/ai-mcp-client/index.md",
  "en/components/extension/ai/components/mcp-server.md": "en/pages/ai-mcp-server/index.md",
  "en/components/extension/ai/components/jev.md": "en/pages/ai-jev/index.md",
  "en/components/extension/ai/components/jev-filter.md": "en/pages/ai-jev-filter/index.md",
  "en/guide/advanced/09.At-Most-Once Execution.md": "en/pages/locker/index.md",
  "en/server/12.Distributed Deployment.md": "en/pages/rulego-server-distributed/index.md"
}
